---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    # Network Integrator 91
    sha512_password: "$6$ZMTiXhLqBo7v1si1$sytOdfL9pAFj4paRrqnQeolINyi1zTrBECVQimMvYRAR5wL8RQa02Qet9Jz7D6PXANdb.CEyeVrLbWv8INv7K0"

  # demo:
  #   privilege: 15
  #   role: network-admin
  #   sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"


# Cloud Vision server information
cvp_instance_ip: 10.83.28.164
cvp_ingestauth_key: ''
# cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_gateway: 10.73.0.1

# dns servers.
name_servers:
  - 1.1.1.1

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - fr.pool.ntp.org

# Required for EOS State Validation
dns_domain: eve.emea.lab
validation_mode_loose: true

### Connection information
ansible_become: true
ansible_become_method: enable
ansible_httpapi_port: '{{ansible_port}}'
ansible_httpapi_host: '{{ ansible_host }}'
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: yes