---
port_profiles:
  ALL:
    mode: trunk
    vlans: "110-114,210,211"
  TENANT_A:
    mode: access
    vlans: "110"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  #################################
  # POD servers
  #################################
  POD01-SRV:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF1A]
        profile: ALL
  POD02-SRV:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF2A]
        profile: ALL

  #################################
  # Fake servers
  #################################
  server01_MLAG:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0, Eth1]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [DC1-LEAF1A, DC1-LEAF1B]
        profile: ALL
        port_channel:
          state: present
          description: data
          mode: active
  server02_MLAG:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [Eth0, Eth1]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [DC1-LEAF2A, DC1-LEAF2B]
        profile: ALL
        port_channel:
          state: present
          description: data
          mode: active
  server03_ESI:
    rack: RackC
    adapters:
      - type: nic
        server_ports: [Eth0, Eth1]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [DC1-LEAF3A, DC1-LEAF4A]
        port_channel:
          state: present
          description: data
          mode: active
          esi: 0303:0202:0101
        profile: ALL
