---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: EAPI_FABRIC

# underlay_routing_protocol: isis
# overlay_routing_protocol: ibgp

# AS Number to use when overlay_routing_protocol=ibgp
bgp_as: 65000

# ISIS Parameters when underlay_routing_protocol=ISIS
isis_area_id: "49.0001"
isis_site_id: "0001"

# OSPF Parameters when underlay_routing_protocol=OSPF
underlay_ospf_process_id: 100
underlay_ospf_area: 0.0.0.0
underlay_ospf_max_lsa: 12000

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.255.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    EAPI-SPINE1:
      id: 1
      evpn_role: server
      mgmt_ip: 10.73.254.1/24
      mac_address: '0c:1d:c0:1d:62:01'
    EAPI-SPINE2:
      id: 2
      evpn_role: server
      mgmt_ip: 10.73.254.2/24
      mac_address: '0c:1d:c0:1d:62:02'


# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65101
    spines: [EAPI-SPINE1, EAPI-SPINE2]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_role: client
    evpn_route_servers: [EAPI-SPINE1, EAPI-SPINE2]
  node_groups:
    EAPI_LEAF1:
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-LEAF1A:
          id: 1
          mgmt_ip: 10.73.254.11/24
          spine_interfaces: [Ethernet1, Ethernet1]
          mac_address: '0c:1d:c0:1d:62:01'
        EAPI-LEAF1B:
          id: 2
          mgmt_ip: 10.73.254.12/24
          spine_interfaces: [Ethernet2, Ethernet2]
          mac_address: '0c:1d:c0:1d:62:01'
    EAPI_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-LEAF2A:
          id: 3
          mgmt_ip: 10.73.254.13/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet3, Ethernet3]
        EAPI-LEAF2B:
          id: 4
          mgmt_ip: 10.73.254.14/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet4, Ethernet4]
    EAPI_LEAF_ESI:
      mlag: false
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD03', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-LEAF3A:
          id: 5
          bgp_as: 65103
          mgmt_ip: 10.73.254.17/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet7, Ethernet7]
        EAPI-LEAF4A:
          id: 6
          bgp_as: 65104
          mgmt_ip: 10.73.254.18/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet8, Ethernet8]
    EAPI_BL01:
      bgp_as: 65105
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'BORDER', 'DC1' ]
      nodes:
        EAPI-BL01A:
          id: 7
          mgmt_ip: 10.73.254.15/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet5, Ethernet5]
        EAPI-BL01B:
          id: 8
          mgmt_ip: 10.73.254.16/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet6, Ethernet6]

l2leaf:
  defaults:
    platform: vEOS-LAB
    parent_l3leafs: [ EAPI-LEAF1A, EAPI-LEAF1B ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    EAPI_L2LEAF1:
      parent_l3leafs: [ EAPI-LEAF1A, EAPI-LEAF1B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD01', 'DC1' ]
        # tags: [ border ]
      nodes:
        EAPI-AGG01:
          id: 9
          mgmt_ip: 10.73.254.21/24
          mac_address: '0c:1d:c0:1d:62:01'
          l3leaf_interfaces: [ Ethernet5, Ethernet5 ]
    EAPI_L2LEAF2:
      parent_l3leafs: [ EAPI-LEAF2A, EAPI-LEAF2B ]
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD02', 'DC1' ]
      nodes:
        EAPI-AGG02:
          id: 10
          mgmt_ip: 10.73.254.22/24
          mac_address: '0c:1d:c0:1d:62:01'
          l3leaf_interfaces: [ Ethernet5, Ethernet5 ]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
